# Change Log {#change-log}

The current version of this Guide is v.0.2.


## v.0.0 {-}

The first version of the guide contains all of the key information on HDA and how to prepare for the program.

## v.0.1 {-}

Minor updates to correct minor typos after review by the administrative team of all term dates and contact information.

## v.0.2 {-}

Previous versions were created by Mr Thomas Wright, a previous teaching fellow and student of the MSc HDA-ML. The current version has been updated by Dr Sabrina Rodrigues and updates include:

* corrections to minor typos
* changes to dates
* corrections of figure numbering
* updates to latest release numbers

If you notice any typos or some releases need to be updated, please contact Dr Sabrina Rodrigues with any changes or suggestions.

## v.0.3 {-}

* Minor changes to end of Term 2 dates
* Included specifications around Term 3 split into Project overview and preparation for presentation
* Removal of Python optional course as this has now been incorporated into CDM.
